[character]      # The name of the module we are configuring is "character"
format = " $symbol "
success_symbol = "[λ](bold blue)"     # The "symbol" segment is being set to "➜"
vicmd_symbol = "[](bold green)"
error_symbol = "[](bold red)"
