#! /bin/sh
# Bspwm Configuration file
# MineBill: 23/02/2021
# vim:ft=sh

pgrep -x sxhkd > /dev/null || sxhkd &
wmname LG3D
~/init.sh

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DVI-D-0 -d 0
sleep 0.2
bspc wm -O HDMI-0 DVI-D-0

bspc config border_width         3
bspc config window_gap          5

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc config focused_border_color \#d71f26

bspc rule -a Alacritty:num_pad state=floating
bspc rule -a Alacritty:floating state=floating
bspc rule -a mpv state=floating
