#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0  -d 1 2 3 4 5 6 7 8 9
bspc monitor DVI-D-0 -d 10

unfocused=#4F5B66
focused=#43A5F5
select=#43A5F5
padding=0

for side in top right bottom left; do
    bspc config ${side}_padding $padding
done

bspc config normal_border_color   $unfocused
bspc config active_border_color   $unfocused
bspc config focused_border_color  $focused
bspc config presel_border_color   $select
bspc config border_width          3
bspc config window_gap            4
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config paddingless_monocle   true
bspc config single_monocle        false

# RULES
#bspc rule -a Gimp      desktop='^8'   state=floating   follow=on
#bspc rule -a Chromium  desktop='^2'
#bspc rule -a mplayer2  state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

[[ ! $(pidof -x sxhkd) ]] && sxhkd &

~/init.sh
 # vim: set ft=sh:
